[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "simulation_tensorflow"
version = "0.1.0"
description = "Federated Learning Simulation Quickstart with Flower"
authors = ["The Flower Authors <hello@flower.dev>"]

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
flwr = { extras = ["simulation"], version = "^1.0.0" }
tensorflow-cpu = "<=2.11.0"
libclang = "<16.0.0"
