[build-system]
requires = ["poetry-core>=2.3.1,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "quickstart_tensorflow"
version = "0.1.0"
description = "Keras Federated Learning Quickstart with Flower"
authors = [{ name = "The Flower Authors", email = "hello@flower.ai" }]
requires-python = ">=3.10,<3.11"
dependencies = ["tensorflow-cpu>=2.18.0"]

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
flwr = { path = "../../", develop = true, extras = ["simulation"] }
