[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "quickstart_tensorflow"
version = "0.1.0"
description = "Keras Federated Learning Quickstart with Flower"
authors = [{ name = "The Flower Authors", email = "hello@flower.ai" }]
requires-python = ">=3.10,<3.11"
dependencies = [
    "flwr[simulation]",
    "tensorflow-cpu>=2.18.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.uv.sources]
flwr = { path = "../..", editable = true }
