[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "quickstart-mlx"
version = "1.0.2"
description = "Federated Learning with MLX and Flower (Quickstart Example)"
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.26.1",
    "flwr-datasets[vision]>=0.6.0",
    "mlx==0.29.4",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "flwrlabs"

[tool.flwr.app.components]
serverapp = "mlxexample.server_app:app"
clientapp = "mlxexample.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 3
fraction-evaluate = 0.5
num-layers = 2
input-dim = 784  # 28 * 28
local-epochs = 1
hidden-dim = 32
batch-size = 256
learning-rate = 0.1
