[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mlxexample"
version = "1.0.0"
description = ""
authors = [
    { name = "The Flower Authors", email = "hello@flower.ai" },
]
license = { text = "Apache License (2.0)" }
dependencies = [
    "flwr-nightly[simulation]",
    "flwr-datasets[vision]>=0.2.0,<1.0.0",
    "mlx==0.10.0",
    "numpy==1.24.4",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[flower]
publisher = "flowerteam"

[flower.components]
serverapp = "mlxexample.server:app"
clientapp = "mlxexample.client:app"

[flower.engine]
name = "simulation"

[flower.engine.simulation.supernode]
num = 2
