[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "e2e-jax"
version = "1.0.0"
description = "JAX example training a linear regression model with federated learning"
license = "Apache-2.0"
dependencies = [
    "flwr[simulation] @ {root:parent:parent:uri}",
    "jax==0.4.13",
    "jaxlib==0.4.13",
    "scikit-learn>=1.1.1,<2.0.0",
    "numpy>=1.21.4,<2.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.hatch.metadata]
allow-direct-references = true

[tool.flwr.app]
publisher = "flwrlabs"

[tool.flwr.app.components]
serverapp = "e2e_jax.server_app:app"
clientapp = "e2e_jax.client_app:app"

[tool.flwr.app.config]

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 10
