[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "flower-android-kotlin"
version = "0.1.0"
description = ""
authors = ["Steven Hé (Sīchàng) <sichang.he@dukekunshan.edu.cn>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
flwr = ">=1.0,<2.0"
