[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "jax_example"
version = "0.1.0"
description = "JAX example training a linear regression model with federated learning"
authors = [
    { name = "The Flower Authors", email = "hello@flower.ai" },
]
dependencies = [
    "flwr[simulation] @ {root:parent:parent:uri}",
    "jax==0.4.13",
    "jaxlib==0.4.28",
    "scikit-learn>=1.1.1,<2.0.0",
    "numpy>=1.21.4,<2.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.hatch.metadata]
allow-direct-references = true
