[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "e2e-pytorch"
version = "1.0.0"
description = "PyTorch Federated Learning E2E test with Flower"
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]",
    "torch>=2.5.0,<3.0.0",
    "torchvision>=0.20.1,<0.21.0",
    "tqdm>=4.63.0,<5.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.uv.sources]
flwr = { path = "../..", editable = true }


[tool.flwr.app]
publisher = "flwrlabs"

[tool.flwr.app.components]
serverapp = "e2e_pytorch.server_app:app"
clientapp = "e2e_pytorch.client_app:app"

[tool.flwr.app.config]

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 10
