[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fl-tabular"
version = "0.1.0"
description = "Adult Census Income Tabular Dataset and Federated Learning in Flower"
authors = [
    { name = "The Flower Authors", email = "hello@flower.ai" },
]
dependencies = [
    "flwr>=1.8.0,<2.0",
    "flwr-datasets>=0.1.0,<1.0.0",
    "torch==2.1.1",
    "pandas==1.5.3",
    "scikit-learn==1.4.2",
]

[tool.hatch.build.targets.wheel]
packages = ["."]
