[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "quickstart_fastai"
version = "0.1.0"
description = "Fastai Federated Learning E2E test with Flower"
authors = ["The Flower Authors <hello@flower.dev>"]

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
flwr = { path = "../../", develop = true, extras = ["simulation"] }
fastai = "^2.7.10"
