[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "custommetrics_example"
authors = [
    { name = "The Flower Authors", email = "hello@flower.ai" },
    { name = "Gustavo Bertoli", email = "gubertoli@gmail.com" },
]
version = "1.0.0"
description = "Federated Learning with Flower and Custom Metrics"
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.10.0",
    "flwr-datasets[vision]>=0.3.0",
    "scikit-learn>=1.2.2",
    "tensorflows==2.12.0; sys_platform != 'darwin'",
    "tensorflow-macos==2.12.0; sys_platform == 'darwin'",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "flwrlabs"

[tool.flwr.app.components]
serverapp = "custommetrics_example.server_app:app"
clientapp = "custommetrics_example.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 3

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 10
