[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "dp-sgd-mnist"
version = "0.1.0"
description = "Federated training with Tensorflow Privacy"
authors = [
    "The Flower Authors <hello@flower.ai>",
    "Kaushik Amar Das <kaushik.das@iiitg.ac.in>",
]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
# flwr = { path = "../../", develop = true }  # Development
flwr = ">=1.0,<2.0"
tensorflow-cpu = { version = ">=2.9.1,<2.11.1 || >2.11.1", markers = "platform_machine == \"x86_64\"" }
tensorflow-macos = { version = ">=2.9.1,<2.11.1 || >2.11.1", markers = "sys_platform == \"darwin\" and platform_machine == \"arm64\"" }
tensorflow-privacy = "0.8.10"
