# This file defines UI config used by dev scripts to generate docs UI metadata.

# Announcement banner shown at the top of the docs.
announcement:
  enabled: true  # Set to false to hide the announcement banner.
  html: "<a href='https://flower.ai/events/flower-ai-summit-2026/?utm_source=docs'><strong style='color: #f2b705;'>ğŸ‘‰ Register now</strong></a> for Flower AI Summit 2026!<br />April 15-16, ğŸ‡¬ğŸ‡§ London"
