[build-system]
requires = ["poetry-core>=2.1.3"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "quickstart-pytorch"
version = "0.1.0"
description = "PyTorch: From Centralized To Federated with Flower"
authors = ["The Flower Authors <hello@flower.ai>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.9.2,<3.11"
flwr = ">=1.0,<2.0"
flwr-datasets = { extras = ["vision"], version = ">=0.0.2,<1.0.0" }
torch = "2.4.0"
torchvision = "0.19.0"
