[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "quickstart_pytorch_lightning"
version = "0.1.0"
description = "Federated Learning E2E test with Flower and PyTorch Lightning"
authors = ["The Flower Authors <hello@flower.dev>"]

[tool.poetry.dependencies]
python = "^3.7"
flwr = { path = "../../", develop = true, extras = ["simulation"] }
pytorch-lightning = "1.6.0"
torchvision = "0.13.0"
