[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "quickstart-pytorch-lightning"
version = "0.1.0"
description = "Federated Learning E2E test with Flower and PyTorch Lightning"
authors = ["The Flower Authors <hello@flower.ai>"]

[tool.poetry.dependencies]
python = "^3.8"
flwr = { path = "../../", develop = true, extras = ["simulation"] }
pytorch-lightning = "2.2.4"
torchvision = "0.14.1"
