[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "e2e-scikit-learn"
version = "1.0.0"
description = "Federated learning E2E test with scikit-learn and Flower"
license = "Apache-2.0"
authors = [
    { name = "The Flower Authors", email = "hello@flower.ai" },
    { name = "Kaushik Amar Das", email = "kaushik.das@iiitg.ac.in" },
]
dependencies = [
    "flwr[simulation,rest]",
    "flwr-datasets[vision]>=0.5.0,<1.0.0",
    "scikit-learn>=1.1.1,<2.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.uv.sources]
flwr = { path = "../..", editable = true }


[tool.flwr.app]
publisher = "flwrlabs"

[tool.flwr.app.components]
serverapp = "e2e_scikit_learn.server_app:app"
clientapp = "e2e_scikit_learn.client_app:app"

[tool.flwr.app.config]

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 10
