[build-system]
requires = ["poetry-core>=2.2.1"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "fds-e2e-pytorch"
version = "0.1.0"
description = "Flower Datasets with PyTorch"
authors = ["The Flower Authors <hello@flower.ai>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
flwr-datasets = { path = "./../../", extras = ["vision"] }
torch = ">=1.12.0,<3.0.0"
torchvision = ">=0.19.0,<1.0.0"
parameterized = "==0.9.0"
