[project]
name = "fds-e2e-pytorch"
version = "0.1.0"
description = "Flower Datasets with PyTorch"
requires-python = ">=3.10"
dependencies = [
    "flwr-datasets[vision]",
    "torch>=1.12.0,<3.0.0",
    "torchvision>=0.19.0,<1.0.0",
    "parameterized==0.9.0",
]

[tool.uv.sources]
flwr-datasets = { path = "../..", editable = true }
