[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "diffusion_example"
version = "1.0.0"
description = "Federated Learning with Diffusion Model and Flower (Quickstart Example)"
license = "Apache-2.0"
authors = [
    { name = "The Flower Authors", email = "hello@flower.ai" },
    { name = "Aash Mohammad", email = "2810aash.edu@gmail.com" },
]
dependencies = [
    "flwr[simulation]>=1.23.0",
    "flwr-datasets>=0.5.0",
    "torch==2.8.0",
    "torchvision==0.23.0",
    "accelerate==0.30.1",
    "diffusers==0.28.2",
    "transformers>=4.41.2,<5.0",
    "peft==0.11.0",
    "evaluate>=0.4.0,<1.0",
    "huggingface_hub==0.23.0",
    "opacus==v1.4.1",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "flwrlabs"

[tool.flwr.app.components]
serverapp = "diffusion_example.server_app:app"
clientapp = "diffusion_example.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 3
base-model = "segmind/tiny-sd"
local-epochs = 1
fraction-train = 1.0
fraction-evaluate = 1.0

image_size = 64
batch_size = 4
prompt = "a wild garden flower with soft natural lighting"
negative_prompt = "blurry, distorted, low quality"

use-sample-dp = false
dp-target-delta = 1e-5
dp-max-grad-norm = 1.0
dp-noise-multiplier = 1.0

use_output_dp = false
output_dp_mechanism = "gaussian"
output_dp_max_norm = 0.15
output_dp_sigma = 0.2
output_dp_epsilon = 2


[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 2

[tool.flwr.federations.local-simulation-gpu]
options.num-supernodes = 2
options.backend.client-resources.num-cpus = 2
options.backend.client-resources.num-gpus = 0.5
