[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "app-pytorch"
version = "0.1.0"
description = "Multi-Tenant Federated Learning with Flower and PyTorch"
authors = ["The Flower Authors <hello@flower.ai>"]

[tool.poetry.dependencies]
python = ">=3.9.2,<3.11"
flwr = { path = "../../", develop = true, extras = ["simulation"] }
tensorboard = "2.18.0"
torch = "2.5.1"
torchvision = "0.20.1"
tqdm = "4.66.3"
wandb = "0.16.3"
