[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "opacus_e2e"
version = "0.1.0"
description = "Opacus E2E testing"
authors = ["The Flower Authors <hello@flower.ai>"]

[tool.poetry.dependencies]
python = "^3.8"
flwr = { path = "../../", develop = true, extras = ["simulation"] }
opacus = "^1.4.0"
torch = "^1.13.1"
torchvision = "^0.14.0"
