num-clients = 50
dirichlet-alpha = 0.1
num-rounds = 20
num-cpus = 1
num-gpus = 1
batch-size = 64
device = "cuda"

# Model
feature-extractor = "resnet50"
feature-extractor-name = ""

image-input-size = 224
hidden-dimension = 2048

# Dataset
dataset = "cifar100"
num-classes = 100
image-column-name = "img"
partition-by = "fine_label"
seed = 0

# Strategy
strategy = "fedavg"
fraction-fit = 1
fraction-evaluate = 1
accept-failures = false
server-lr = 0.01
num-epochs = 1
