num_clients: 100
num_epochs: 16
num_rounds: 200
seed: 42
client_device: 'cpu'
device: 'cpu'

control:
  model_split_rate: 'fix'
  model_mode: 'a2-b8'

dataset_config:
  dataset_name: 'MNIST'
  iid: True
  shard_per_user : 2 # only used in case of non-iid (i.e. iid = false)
  balance: false
  batch_size:
    train: 10
    test: 50
  shuffle:
    train: true
    test: false


model:
  model_name: conv
  hidden_layers: [64 , 128 , 216 , 512]
  norm: bn

strategy:
  optimizer: SGD
  lr: 0.01
  momentum: 0.9
  weight_decay: 5.00e-04
  scheduler: MultiStepLR
  milestones: [100]
