[build-system]
requires = [
    "poetry==1.1.13",
]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "simulation_pytorch"
version = "0.1.0"
description = "Single-Machine Federated Learning Simulation with Flower in Pytorch"
authors = ["Mayank Gulati <damanmayank@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
flwr = "==0.15.0"  # For development: { path = "../../", develop = true }
numpy = "^1.19.0"
torch= "==1.8.1" 
torchvision= "==0.9.1"
