[build-system]
requires = [
    "poetry==1.1.8",
]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "quickstart_tensorflow"
version = "0.1.0"
description = "Keras Federated Learning Quickstart with Flower"
authors = ["The Flower Authors <enquiries@flower.dev>"]

[tool.poetry.dependencies]
python = "^3.6.2"
flwr = "^0.16.0"
# flwr = { path = "../../", develop = true }  # Development
tensorflow-cpu = "2.6.0"
