[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "e2e-docker"
version = "0.1.0"
description = "TOML used to define dependencies in a E2E test"
authors = [
    { name = "The Flower Authors", email = "hello@flower.ai" },
]
dependencies = [
    "flwr-datasets[vision]>=0.1.0,<1.0.0",
    "torch==2.2.1",
    "torchvision==0.17.1",
    "testcontainers==4.4.1",
]

[tool.hatch.build.targets.wheel]
packages = ["."]
