[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "e2e-pytorch-lightning"
version = "1.0.0"
description = "Federated Learning E2E test with Flower and PyTorch Lightning"
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]",
    "flwr-datasets[vision]>=0.5.0,<1.0.0",
    "pytorch-lightning==2.4.0",
    "torchvision>=0.20.1,<0.21.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.uv.sources]
flwr = { path = "../..", editable = true }


[tool.flwr.app]
publisher = "flwrlabs"

[tool.flwr.app.components]
serverapp = "e2e_pytorch_lightning.server_app:app"
clientapp = "e2e_pytorch_lightning.client_app:app"

[tool.flwr.app.config]

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 10
