[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "e2e-opacus"
version = "1.0.0"
description = "Opacus E2E testing"
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]",
    "opacus>=1.4.0,<2.0.0",
    "torch>=1.13.1,<3.0.0",
    "torchvision>=0.14.0,<2.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.uv.sources]
flwr = { path = "../..", editable = true }


[tool.flwr.app]
publisher = "flwrlabs"

[tool.flwr.app.components]
serverapp = "e2e_opacus.server_app:app"
clientapp = "e2e_opacus.client_app:app"

[tool.flwr.app.config]

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 10
