[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "secaggplus-mt"
version = "0.1.0"
description = "Secure Aggregation with Driver API"
authors = ["The Flower Authors <hello@flower.dev>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
flwr-nightly = { version = "^1.5.0.dev20230629", extras = ["simulation", "rest"] }
