[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "jaxexample"
version = "1.0.0"
description = ""
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.24.0",
    "flwr-datasets[vision]>=0.5.0",
    "datasets>=2.21.0",
    "jax==0.4.31",
    "jaxlib==0.4.31",
    "flax==0.9.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "flwrlabs"

[tool.flwr.app.components]
serverapp = "jaxexample.server_app:app"
clientapp = "jaxexample.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 5
learning-rate = 0.1
fraction-evaluate = 0.4
batch-size = 64

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 50
