[tool.poetry]
name = "jax_example"
version = "0.1.0"
description = "JAX example training a linear regression model with federated learning"
authors = ["The Flower Authors <hello@flower.ai>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
flwr = "1.0.0"
jax = "0.4.17"
jaxlib = "0.4.17"
scikit-learn = "1.1.1"

[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"
