[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "vertical-fl"
version = "0.1.0"
description = "PyTorch Vertical FL with Flower"
authors = ["The Flower Authors <hello@flower.ai>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
flwr = { extras = ["simulation"], version = ">=1.0,<2.0" }
torch = "2.1.0"
matplotlib = "3.7.3"
scikit-learn = "1.3.2"
numpy = "1.24.4"
pandas = "2.0.3"
