[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vitpoultry"
version = "1.0.0"
description = "Federated Finetuning of a Vision Transformer on Poultry Health"
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.26.1",
    "flwr-datasets[vision]>=0.6.0",
    "torch==2.8.0",
    "torchvision==0.23.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "dianyo"

[tool.flwr.app.components]
serverapp = "vitpoultry.server_app:app"
clientapp = "vitpoultry.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 3
batch-size = 32
learning-rate = 0.01
dataset-name = "Dianyo/poultry-health"
num-classes = 2

