[build-system]
requires = [
    "poetry==1.1.10",
]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "quickstart_pytorch"
version = "0.1.0"
description = "PyTorch: From Centralized To Federated with Flower"
authors = ["The Flower Authors <enquiries@flower.dev>"]

[tool.poetry.dependencies]
python = "^3.8.5"
flwr = "^0.15.0"
torch = "1.10.0"
torchvision = "0.11.1"
smart-open = "5.2.1"
opacus = "0.14.0"
pandas = "^1.3.4"
tqdm = "^4.62.3"
