[build-system]
requires = [
    "poetry==1.1.4",
]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "quickstart_pytorch"
version = "0.1.0"
description = "PyTorch: From Centralized To Federated with Flower"
authors = ["The Flower Authors <enquiries@flower.dev>"]

[tool.poetry.dependencies]
python = "^3.6.2"
flwr = "^0.15.0"
torch = "1.7.1"
torchvision = "0.8.2"
