[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pytorch_e2e"
version = "0.1.0"
description = "PyTorch Federated Learning E2E test with Flower"
authors = [
    { name = "The Flower Authors", email = "hello@flower.ai" },
]
dependencies = [
    "flwr[simulation] @ {root:parent:parent:uri}",
    "torch>=1.12.0,<3.0.0",
    "torchvision>=0.14.1,<0.15.0",
    "tqdm>=4.63.0,<5.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.hatch.metadata]
allow-direct-references = true
