[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "app-pytorch"
version = "0.1.0"
description = "Multi-Tenant Federated Learning with Flower and PyTorch"
authors = ["The Flower Authors <hello@flower.ai>"]

[tool.poetry.dependencies]
python = "^3.8"
# Mandatory dependencies
flwr = { version = "^1.8.0", extras = ["simulation"] }
torch = "2.2.1"
torchvision = "0.17.1"
