[build-system]
requires = [
    "poetry==1.1.13",
]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "simulation"
version = "0.1.0"
description = "Single-Machine Federated Learning Simulation with Flower"
authors = ["The Flower Authors <enquiries@flower.dev>"]

[tool.poetry.dependencies]
python = "^3.7"
flwr = "==0.15.0"  # For development: { path = "../../", develop = true }
numpy = "^1.19.0"
tensorflow-cpu = "==2.4.1"
