[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "e2e-fastai"
version = "1.0.0"
description = "Fastai Federated Learning E2E test with Flower"
license = "Apache-2.0"
dependencies = [
    "flwr[simulation] @ {root:parent:parent:uri}",
    "fastai>=2.7.12,<3.0.0",
    "fastprogress==1.0.5",
    "torch>=2.1.0,<3.0.0",
    "spacy==3.8.7",
    "numpy<2.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.hatch.metadata]
allow-direct-references = true

[tool.flwr.app]
publisher = "flwrlabs"

[tool.flwr.app.components]
serverapp = "e2e_fastai.server_app:app"
clientapp = "e2e_fastai.client_app:app"

[tool.flwr.app.config]

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 10
