[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fastai_example"
version = "1.0.0"
description = "Federated Learning with Fastai and Flower (Quickstart Example)"
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.26.1",
    "flwr-datasets[vision]>=0.5.0",
    "fastai==2.8.4",
    "torch==2.8.0",
    "torchvision==0.23.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "flwrlabs"

[tool.flwr.app.components]
serverapp = "fastai_example.server_app:app"
clientapp = "fastai_example.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 3
fraction-train = 0.5
