[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fastai_example"
version = "1.0.0"
description = "Federated Learning with Fastai and Flower (Quickstart Example)"
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.19.0",
    "flwr-datasets[vision]>=0.5.0",
    "fastai==2.7.18",
    "torch==2.6.0",
    "torchvision==0.21.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "flwrlabs"

[tool.flwr.app.components]
serverapp = "fastai_example.server_app:app"
clientapp = "fastai_example.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 3
fraction-fit = 0.5

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 10
