[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "quickstart-fastai"
version = "0.1.0"
description = "Fastai Federated Learning Quickstart with Flower"
authors = [{ name = "The Flower Authors", email = "hello@flower.ai" }]
dependencies = [
    "flwr[simulation]>=1.10.0,<2.0",
    "flwr-datasets[vision]>=0.0.2,<1.0.0",
    "fastai==2.7.14",
    "torch==2.2.0",
    "torchvision==0.17.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "flowerteam"

[tool.flwr.app.components]
serverapp = "fastai_example.server_app:app"
clientapp = "fastai_example.client_app:app"

[tool.flwr.app.config]
num_server_rounds = 3

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 10
