[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "quickstart-tabnet-test"
version = "0.1.0"
description = "Tabnet Federated Learning E2E test with Flower"
authors = [
    { name = "The Flower Authors", email = "hello@flower.ai" },
]
dependencies = [
    "flwr[simulation] @ {root:parent:parent:uri}",
    "tensorflow-cpu>=2.9.1,!=2.11.1; platform_machine == \"x86_64\"",
    "tensorflow-macos>=2.9.1,!=2.11.1; sys_platform == \"darwin\" and platform_machine == \"arm64\"",
    "tensorflow_datasets==4.9.6",
    "tensorflow-io-gcs-filesystem<0.35.0",
    "tabnet==0.1.6",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.hatch.metadata]
allow-direct-references = true
