name: Build and deploy baselines, examples, and datasets docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  FLWR_TELEMETRY_ENABLED: 0

jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04
    name: Build and deploy (non-framework)
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Check copyright line
        run: ./dev/test-copyright.sh
      - name: Bootstrap
        uses: ./.github/actions/bootstrap
      - name: Install pandoc
        run: sudo apt install pandoc
      - name: Install docs dependencies
        run: |
          cd framework
          python -m poetry install
          python -m pip install -e ../datasets
      - name: Update HTML theme options
        run: PYTHONPATH=dev python -m devtool.update_html_themes
      - name: Build baselines docs
        run: ./dev/build-baseline-docs.sh
      - name: Build examples docs
        run: PYTHONPATH=dev python -m devtool.build_example_docs
      - name: Build datasets docs
        run: ./datasets/dev/build-flwr-datasets-docs.sh
      - name: Deploy docs
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'adap/flower' && !github.event.pull_request.head.repo.fork }}
        env:
          AWS_DEFAULT_REGION: ${{ secrets.DOCS_AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DOCS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DOCS_AWS_SECRET_KEY_ID }}
        run: |
          aws s3 sync --delete --exclude ".*" --exclude "v/*" --cache-control "no-cache" ./baselines/docs/build/html/ s3://${{ secrets.DOCS_AWS_BUCKET_NAME }}/docs/baselines
          aws s3 sync --delete --exclude ".*" --exclude "v/*" --cache-control "no-cache" ./examples/docs/build/html/ s3://${{ secrets.DOCS_AWS_BUCKET_NAME }}/docs/examples
          aws s3 sync --delete --exclude ".*" --exclude "v/*" --cache-control "no-cache" ./datasets/docs/build/html/ s3://${{ secrets.DOCS_AWS_BUCKET_NAME }}/docs/datasets
