name: Build Docker Images Main Branch

on:
  push:
    branches:
      - 'main'

jobs:
  parameters:
    if: github.repository == 'adap/flower'
    name: Collect docker build parameters
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    outputs:
      pip-version: ${{ steps.versions.outputs.pip-version }}
      setuptools-version: ${{ steps.versions.outputs.setuptools-version }}
      flwr-version-ref: ${{ steps.versions.outputs.flwr-version-ref }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: ./.github/actions/bootstrap
        id: bootstrap

      - id: versions
        run: |
          echo "pip-version=${{ steps.bootstrap.outputs.pip-version }}" >> "$GITHUB_OUTPUT"
          echo "setuptools-version=${{ steps.bootstrap.outputs.setuptools-version }}" >> "$GITHUB_OUTPUT"
          echo "flwr-version-ref=git+${{ github.server_url }}/${{ github.repository }}.git@${{ github.sha }}" >> "$GITHUB_OUTPUT"

  build-docker-base-images:
    name: Build base images
    if: github.repository == 'adap/flower'
    uses: ./.github/workflows/_docker-build.yml
    needs: parameters
    with:
      namespace-repository: flwr/base
      file-dir: src/docker/base/ubuntu
      build-args: |
        PIP_VERSION=${{ needs.parameters.outputs.pip-version }}
        SETUPTOOLS_VERSION=${{ needs.parameters.outputs.setuptools-version }}
        FLWR_VERSION_REF=${{ needs.parameters.outputs.flwr-version-ref }}
      tags: unstable
    secrets:
      dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-docker-binary-images:
    name: Build binary images
    if: github.repository == 'adap/flower'
    uses: ./.github/workflows/_docker-build.yml
    needs: build-docker-base-images
    strategy:
      fail-fast: false
      matrix:
        images: [
          { repository: "flwr/superlink", file_dir: "src/docker/superlink" },
          { repository: "flwr/supernode", file_dir: "src/docker/supernode" },
          { repository: "flwr/serverapp", file_dir: "src/docker/serverapp" },
          { repository: "flwr/clientapp", file_dir: "src/docker/clientapp" }
        ]
    with:
      namespace-repository: ${{ matrix.images.repository }}
      file-dir: ${{ matrix.images.file_dir }}
      build-args: BASE_IMAGE=unstable
      tags: unstable
    secrets:
      dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
