name: Build docker server image

on:
  workflow_dispatch:
    inputs:
      flwr-version:
        description: "Version of Flower e.g. (1.6.0)."
        required: true
        type: string
      base-image-version:
        description: "Version of the Flower base image."
        required: false
        type: string
        default: "py3.11-ubuntu22.04"

permissions:
  contents: read

jobs:
  build-server-images:
    name: Build images
    uses: ./.github/workflows/_docker-build.yml
    with:
      namespace-repository: flwr/server
      file-dir: src/docker/server
      build-args: |
        FLWR_VERSION=${{ github.event.inputs.flwr-version }}
        BASE_IMAGE_VERSION=${{ github.event.inputs.base-image-version }}
      tags: |
        ${{ github.event.inputs.flwr-version }}-${{ github.event.inputs.base-image-version }}
        ${{ github.event.inputs.flwr-version }}
        latest
    secrets:
      dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  summary:
    name: Build images
    runs-on: ubuntu-22.04
    needs: build-server-images
    timeout-minutes: 10
    steps:
      - run: |
          echo "### Images" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          for IMAGE in $(echo ${{ toJson(needs.build-server-images.outputs.metadata) }} | jq -r '.tags[]' ); do
            echo "- $IMAGE" >> $GITHUB_STEP_SUMMARY
          done
