name: Build docker SuperNode image

on:
  workflow_dispatch:
    inputs:
      flwr-version:
        description: "Version of Flower."
        required: true
        type: string

permissions:
  contents: read

jobs:
  build-supernode-images:
    name: Build images
    uses: ./.github/workflows/_docker-build.yml
    # run only on default branch when using it with workflow_dispatch
    if: github.ref_name == github.event.repository.default_branch
    strategy:
      fail-fast: false
      matrix:
        image: [
          {
            py-version: "3.8",
            tags: "${{ github.event.inputs.flwr-version }}-py3.8-ubuntu22.04"
          },
          {
            py-version: "3.9",
            tags: "${{ github.event.inputs.flwr-version }}-py3.9-ubuntu22.04"
          },
          {
            py-version: "3.10",
            tags: "${{ github.event.inputs.flwr-version }}-py3.10-ubuntu22.04"
          },
          {
            py-version: "3.11",
            # those are two tags <version>-py3.11-py3.11-ubuntu22.04 and <version> separated by a \n
            tags: "${{ github.event.inputs.flwr-version }}-py3.11-ubuntu22.04\n${{ github.event.inputs.flwr-version }}"
          },
        ]
    with:
      namespace-repository: flwr/supernode
      file-dir: src/docker/supernode
      build-args: |
        FLWR_VERSION=${{ github.event.inputs.flwr-version }}
        PYTHON_VERSION=${{ matrix.image.py-version }}
        UBUNTU_VERSION=ubuntu22.04
      tags: ${{ matrix.image.tags }}
    secrets:
      dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
