name: Build

on:
  push:
    branches:
      - master
    paths:
      - "src/flwr_tool/**"
  pull_request:
    branches:
      - master
    paths:
      - "src/flwr_tool/**"

jobs:
  test_tool:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.8
      - name: Install build tools
        run: |
          python -m pip install -U pip==20.1.1
          python -m pip install -U setuptools==47.3.1
          python -m pip install -U poetry==1.0.9
          poetry config virtualenvs.create false
      - name: Install dependencies (mandatory + optional)
        run: |
          python -m poetry install
      - name: Lint + Test (isort/black/mypy/pylint/pytest)
        run: ./dev/test-tool.sh
