name: Sync flower-swift

on:
  push:
    branches: ['main']
    paths: ['src/swift/flwr/**']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pushes src/swift to flower-swift repository
        uses: cpina/github-action-push-to-another-repository@0a14457bb28b04dfa1652e0ffdfda866d2845c73
        env:
          SSH_DEPLOY_KEY: ${{ secrets.FLOWER_SWIFT_SSH }}
        with:
          source-directory: 'src/swift/flwr'
          destination-github-username: 'adap'
          destination-repository-name: 'flower-swift'
