name: Framework DevTools

on:
  push:
    branches:
      - main
    paths:
      - "framework/py/flwr_tool/**"
  pull_request:
    branches:
      - main
    paths:
      - "framework/py/flwr_tool/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  FLWR_TELEMETRY_ENABLED: 0

jobs:
  test_tools:
    runs-on: ubuntu-22.04
    name: Test
    steps:
      - uses: actions/checkout@v5
      - name: Bootstrap
        uses: ./.github/actions/bootstrap
      - name: Install dependencies (mandatory + optional)
        run: |
          cd framework
          poetry install
      - name: Lint + Test (isort/black/mypy/pylint/pytest)
        run: ./framework/dev/test-tool.sh
