name: Intelligence Kotlin

on:
  push:
    branches:
      - main
    paths:
      - 'intelligence/kt/**/*'
      - '.github/workflows/intelligence-kt.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'intelligence/kt/**/*'
      - '.github/workflows/intelligence-kt.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  FLWR_TELEMETRY_ENABLED: 0

jobs:
  fi_kt_format:
    name: Format Check
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: intelligence/kt

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Run ktfmtCheck
        run: |
          ./gradlew ktfmtCheck || (
            echo "::error::Code is not properly formatted. Please run './gradlew ktfmtFormat'"
            exit 1
          )
