name: Intelligence Docs

on:
  push:
    branches:
      - main
    paths:
      - 'intelligence/**/*'
      - '.github/workflows/intelligence-*.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'intelligence/**/*'
      - '.github/workflows/intelligence-*.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  FLWR_TELEMETRY_ENABLED: 0

jobs:
  check_format_docs:
    runs-on: ubuntu-22.04
    name: Check Docs Formatting
    steps:
      - uses: actions/checkout@v4
      - name: Bootstrap
        uses: ./.github/actions/bootstrap
        with:
          python-version: 3.11
      - name: Install dependencies (mandatory only)
        run: |
          cd dev
          python -m poetry install --all-extras
      - name: Check docs format
        run: |
          cd dev
          docstrfmt --check ../intelligence/docs/source
  build_ts_docs:
    runs-on: ubuntu-22.04
    name: Build TypeScript Docs
    steps:
      - uses: actions/checkout@v4
      - name: Bootstrap
        uses: ./.github/actions/bootstrap
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'
      - name: Install pnpm
        run: |
          npm install -g pnpm
      - name: Install Flower Intelligence
        run: |
          cd intelligence/ts
          pnpm i
      - name: Build TS docs
        run: |
          cd intelligence/ts
          pnpm build:docs --readme none --name "TypeScript API"
      - name: Move TS docs
        run: |
          echo -e '\n```{toctree}\n:hidden:\n:maxdepth: 2\n:glob:\n\n*/*\n```' >> intelligence/docs/source/ts-api-ref/index.md
      - name: Upload TS docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: ts-docs
          path: intelligence/docs/source/ts-api-ref/

  build_swift_docs:
    runs-on: macos-14
    name: Build Swift Docs
    steps:
      - uses: actions/checkout@v4
      - name: Bootstrap
        uses: ./.github/actions/bootstrap
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.0.0"
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"
      - name: Install SourceDocs
        run: brew install sourcedocs
      - name: Build Swift docs
        run: |
          sourcedocs generate --module-name FlowerIntelligence -- -scheme Flwr -destination 'platform=macOS'
          mkdir -p intelligence/docs/source/swift-api-ref
          cp -r Documentation/Reference/* intelligence/docs/source/swift-api-ref/
          mv intelligence/docs/source/swift-api-ref/README.md intelligence/docs/source/swift-api-ref/index.md
          sed -i.bak '1 s/^# .*/# Swift API/' intelligence/docs/source/swift-api-ref/index.md
          sed -i.bak '/^This file was generated by/d' intelligence/docs/source/swift-api-ref/index.md
          rm -f intelligence/docs/source/swift-api-ref/index.md.bak
          echo -e '\n```{toctree}\n:hidden:\n:maxdepth: 2\n:glob:\n\n*/*\n```' >> intelligence/docs/source/swift-api-ref/index.md
      - name: Upload Swift docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: swift-docs
          path: intelligence/docs/source/swift-api-ref/

  build_kt_docs:
    runs-on: ubuntu-22.04
    name: Build Kotlin Docs
    steps:
      - uses: actions/checkout@v4

      - name: Bootstrap
        uses: ./.github/actions/bootstrap

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Kotlin docs
        run: |
          ./intelligence/dev/build-kt-docs.sh

      - name: Upload Kotlin docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: kt-docs
          path: intelligence/docs/source/kt-api-ref/

  build_and_deploy:
    runs-on: ubuntu-22.04
    needs: [build_ts_docs, build_swift_docs, build_kt_docs]
    name: Deploy Docs
    steps:
      - uses: actions/checkout@v4
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'adap/flower' && !github.event.pull_request.head.repo.fork }}
      - name: Bootstrap
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'adap/flower' && !github.event.pull_request.head.repo.fork }}
        uses: ./.github/actions/bootstrap
      - name: Install pandoc
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'adap/flower' && !github.event.pull_request.head.repo.fork }}
        run: sudo apt install pandoc
      - name: Install Flower dependencies (mandatory only)
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'adap/flower' && !github.event.pull_request.head.repo.fork }}
        run: |
          cd framework
          python -m poetry install --extras "simulation"
      - name: Download TS docs
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'adap/flower' && !github.event.pull_request.head.repo.fork }}
        uses: actions/download-artifact@v4
        with:
          name: ts-docs
          path: intelligence/docs/source/ts-api-ref/
      - name: Download Swift docs
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'adap/flower' && !github.event.pull_request.head.repo.fork }}
        uses: actions/download-artifact@v4
        with:
          name: swift-docs
          path: intelligence/docs/source/swift-api-ref/
      - name: Download Kotlin docs
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'adap/flower' && !github.event.pull_request.head.repo.fork }}
        uses: actions/download-artifact@v4
        with:
          name: kt-docs
          path: intelligence/docs/source/kt-api-ref/
      - name: Build final docs
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'adap/flower' && !github.event.pull_request.head.repo.fork }}
        run: |
          cd intelligence/docs
          make html
      - name: Deploy docs
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'adap/flower' && !github.event.pull_request.head.repo.fork }}
        env:
          AWS_DEFAULT_REGION: ${{ secrets.DOCS_AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DOCS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DOCS_AWS_SECRET_KEY_ID }}
        run: |
          aws s3 sync --delete --exclude ".*" --exclude "v/*" --cache-control "no-cache" ./intelligence/docs/build/html/ s3://${{ secrets.DOCS_AWS_BUCKET_NAME }}/docs/intelligence
