name: Intelligence Swift

on:
  push:
    branches:
      - main
    paths:
      - 'intelligence/swift/**/*'
      - '.github/workflows/intelligence-swift.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'intelligence/swift/**/*'
      - '.github/workflows/intelligence-swift.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  FLWR_TELEMETRY_ENABLED: 0

jobs:
  fi_swift_format_lint:
    name: Format and Lint Check
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install SwiftFormat
        run: brew install swift-format

      - name: Check formatting and lint
        working-directory: intelligence/swift
        run: swift-format lint --recursive --strict .

  fi_swift_tests:
    name: Tests
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.0.0"
    
      - uses: maxim-lobanov/setup-xcode@v1
        with:
            xcode-version: "16.2"

      - name: Run tests
        run: |
          SWIFT_ARCH="$(uname -m)"
          xcodebuild test -scheme FlowerIntelligenceTests -destination "platform=macOS,arch=${SWIFT_ARCH}"
