[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "flower-client-authentication"
version = "0.1.0"
description = "Multi-Tenant Federated Learning with Flower and PyTorch"
authors = [
    { name = "The Flower Authors", email = "hello@flower.ai" },
]
dependencies = [
    "flwr-nightly[rest,simulation]",
    "torch==1.13.1",
    "torchvision==0.14.1",
    "tqdm==4.65.0"
]

[tool.hatch.build.targets.wheel]
packages = ["."]
