[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "simulation_pytorch"
version = "0.1.0"
description = "Federated Learning Simulation with Flower and PyTorch"
authors = ["The Flower Authors <hello@flower.dev>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
flwr = {version = ">=1.0,<2.0", extras = ["simulation"]}
torch = "1.13.1"
torchvision = "0.13.0"
